In [5]:
import requests
import pathlib
import xml.etree.ElementTree as ET
import json
import time
import string
import sys
import pandas as pd
from deutsche_bahn_api import ApiAuthentication
from pathlib import Path
import os
import numpy as np
import re
from datetime import datetime, timedelta
from math import radians, cos, sin, asin, sqrt


BASE_DB_API = "https://apis.deutschebahn.com/db-api-marketplace/apis/"
STOP_PLACES_URL = "https://apis.deutschebahn.com/db-api-marketplace/apis/ris-stations/v1/stop-places"
TIMETABLES_V1_URL = BASE_DB_API + "timetables/v1"
RIS_STATION_URL = BASE_DB_API + "ris-station/v1/stations/"
ROOT_DIR = Path(os.getcwd())
DATA_DIR = ROOT_DIR / "data"
RAW_DATA_DIR = ROOT_DIR / "Raw_Data"

DB_CLIENT_ID = "a9f83c55d26c3ee7f48f4ce887ec2a57"
DB_API_KEY = "422cac21a0a83876c75efb8806589ea0"
PKP_API_KEY = "KMjLifnR-a6RGlVgs36-OGG82nZ2gZRuiySF_y-tWSbUMX4LNS3JfBk1hli1B59YIXfdIrIy3ZvwUpkrMueAeA"

header = {
    "DB-Client-Id": DB_CLIENT_ID,
    "DB-Api-Key": DB_API_KEY,
    "accept": "application/xml"
}

header2 = {
    "DB-Client-Id": DB_CLIENT_ID,
    "DB-Api-Key": DB_API_KEY,
    "accept": "application/json"
}

def get_all_stations(country_code="DE"):
    params = {"state": country_code}
    
    response = requests.get(RIS_STATION_URL, headers=header, params=params)
    if response.status_code == 200:
        return response.json().get('stations', [])
    else:   
        print(f"Error: {response.status_code}")
        return []

def haversine(lat1, lon1, lat2, lon2):
    """ Calculate distance in km between two points """
    R = 6371 # Earth radius
    dLat = radians(lat2 - lat1)
    dLon = radians(lon2 - lon1)
    a = sin(dLat/2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dLon/2)**2
    return 2 * R * asin(sqrt(a))

# api credentials validation
api_authentication = ApiAuthentication( DB_CLIENT_ID, DB_API_KEY)
success:bool = api_authentication.test_credentials()
success

/Users/rafael/projects/DOPP_groupB_2025W/.venv/lib/python3.13/site-packages/mpu/string.py:16: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

True

#  Railway stations selection & filtering

First, match train station with selected cities from simplemaps ( Processed_Data/cities_500K). Later for matched cities retrieve required timetables.

Matching should be done geospatially

In [6]:
PROCESSED_DATA_DIR = ROOT_DIR / "Processed_Data"

cities_data = pd.read_csv(PROCESSED_DATA_DIR / "cities_500K.csv")
cities_data.rename(columns={"name_city":"name", "lat_city":"latitude", "lng_city":"longitude","country":"iso_code"}, inplace=True)
cities_data.head()

       name  latitude  longitude iso_code  population  is_capital
0    Vienna   48.2083    16.3725       AT   1973403.0        True
1  Brussels   50.8467     4.3525       BE   1235192.0        True
2   Antwerp   51.2178     4.4003       BE    536079.0       False
3     Sofia   42.7000    23.3300       BG   1383435.0        True
4    Prague   50.0875    14.4214       CZ   1357326.0        True

In [11]:
RIS_STATION_URL = "https://apis.deutschebahn.com/db-api-marketplace/apis/ris-stations/v1/stations"
header_ris = {
    "DB-Client-Id": DB_CLIENT_ID,
    "DB-Api-Key": DB_API_KEY,
    "accept": "application/vnd.de.db.ris+json"
}

res = requests.get(url=RIS_STATION_URL, headers=header_ris, params={"countryCode":"AT"})
res.text

'{"offset":0,"limit":100,"total":5703,"stations":[{"stationID":"1","names":{"DE":{"name":"Aachen Hbf"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"2a","postalCode":"52064","city":"Aachen","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_2","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":6.091499,"latitude":50.7678},"validFrom":"2018-12-31T23:00:00Z","mobilityServiceStaffOnSite":true},{"stationID":"1000","names":{"DE":{"name":"Burkhardswalde-Maxen"}},"metropolis":{},"address":{"street":"Gesundbrunnen","houseNumber":"60c","postalCode":"01809","city":"Müglitztal-Burkhardswalde","state":"Sachsen","country":"DE"},"stationCategory":"CATEGORY_7","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":2,"name":"RB Südost","nameShort":"RB Südost"}},"countryCode":"DE","state":"SN","timeZone":"Europe/Berlin","position":{"longitude":13.8383692,"latitude":50.9251456},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1001","names":{"DE":{"name":"Burkhardtsdorf"}},"metropolis":{},"address":{"street":"Bahnhofstraße","postalCode":"09235","city":"Burkhardtsdorf","state":"Sachsen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB Regio-Netze","organisationalUnit":{"id":5,"name":"Erzgebirgsbahn (EGB)","nameShort":"EGB"}},"countryCode":"DE","state":"SN","timeZone":"Europe/Berlin","validFrom":"1970-01-01T00:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1002","names":{"DE":{"name":"Bürstadt"}},"metropolis":{},"address":{"street":"Bahnhofsallee","houseNumber":"17","postalCode":"68642","city":"Bürstadt","state":"Hessen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":5,"name":"RB Mitte","nameShort":"RB Mitte"}},"countryCode":"DE","state":"HE","timeZone":"Europe/Berlin","position":{"longitude":8.458188,"latitude":49.645769},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1005","names":{"DE":{"name":"Buschow"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"28","postalCode":"14715","city":"Märkisch Luch OT Buschow","state":"Brandenburg","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"BB","timeZone":"Europe/Berlin","position":{"longitude":12.628996,"latitude":52.592203},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1006","names":{"DE":{"name":"Büsenbachtal"}},"metropolis":{},"address":{"street":"Am Büsenbach","houseNumber":"16l","postalCode":"21256","city":"Handeloh-Wörme","state":"Niedersachsen","country":"DE"},"stationCategory":"CATEGORY_7","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"NI","timeZone":"Europe/Berlin","position":{"longitude":9.858592,"latitude":53.269595},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1008","names":{"DE":{"name":"Büsum"}},"metropolis":{},"address":{"street":"Heider Str.","houseNumber":"20","postalCode":"25761","city":"Büsum","state":"Schleswig-Holstein","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"SH","timeZone":"Europe/Berlin","position":{"longitude":8.867113,"latitude":54.133822},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1009","names":{"DE":{"name":"Buttenheim"}},"metropolis":{},"address":{"street":"Am Bahnhof","houseNumber":"2","postalCode":"96146","city":"Altendorf","state":"Bayern","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":7,"name":"RB Süd","nameShort":"RB Süd"}},"countryCode":"DE","state":"BY","timeZone":"Europe/Berlin","position":{"longitude":11.0137296,"latitude":49.7993973},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1011","names":{"DE":{"name":"Büttgen"}},"metropolis":{},"address":{"street":"Driescher Birkhofstraße","houseNumber":"1","postalCode":"41564","city":"Kaarst","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":6.605785,"latitude":51.197208},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1012","names":{"DE":{"name":"Buttstädt"}},"metropolis":{},"address":{"street":"Am Bahnhof","houseNumber":"7","postalCode":"99628","city":"Buttstädt","state":"Thüringen","country":"DE"},"stationCategory":"CATEGORY_7","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":2,"name":"RB Südost","nameShort":"RB Südost"}},"countryCode":"DE","state":"TH","timeZone":"Europe/Berlin","position":{"longitude":11.418412,"latitude":51.126995},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1013","names":{"DE":{"name":"Butzbach"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"8","postalCode":"35510","city":"Butzbach","state":"Hessen","country":"DE"},"stationCategory":"CATEGORY_4","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":5,"name":"RB Mitte","nameShort":"RB Mitte"}},"countryCode":"DE","state":"HE","timeZone":"Europe/Berlin","position":{"longitude":8.669517,"latitude":50.431156},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1014","names":{"DE":{"name":"Bützow"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"40","postalCode":"18246","city":"Bützow","state":"Mecklenburg-Vorpommern","country":"DE"},"stationCategory":"CATEGORY_4","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"MV","timeZone":"Europe/Berlin","position":{"longitude":11.9981942,"latitude":53.8371137},"validFrom":"2018-12-31T23:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1015","names":{"DE":{"name":"Buxtehude"}},"metropolis":{},"address":{"street":"Am Bundesbahnhof","houseNumber":"1","postalCode":"21614","city":"Buxtehude","state":"Niedersachsen","country":"DE"},"stationCategory":"CATEGORY_3","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"NI","timeZone":"Europe/Berlin","position":{"longitude":9.688314,"latitude":53.470491},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1016","names":{"DE":{"name":"Cadenberge"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"41","postalCode":"21781","city":"Cadenberge","state":"Niedersachsen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"NI","timeZone":"Europe/Berlin","position":{"longitude":9.058163,"latitude":53.768071},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1017","names":{"DE":{"name":"Cadolzburg"}},"metropolis":{},"address":{"street":"Bahnhofsplatz","houseNumber":"1","postalCode":"90556","city":"Cadolzburg","state":"Bayern","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":7,"name":"RB Süd","nameShort":"RB Süd"}},"countryCode":"DE","state":"BY","timeZone":"Europe/Berlin","position":{"longitude":10.863611,"latitude":49.460649},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1018","names":{"DE":{"name":"Cainsdorf"}},"metropolis":{},"address":{"street":"Am Hammerwald","postalCode":"08064","city":"Zwickau","state":"Sachsen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB Regio-Netze","organisationalUnit":{"id":5,"name":"Erzgebirgsbahn (EGB)","nameShort":"EGB"}},"countryCode":"DE","state":"SN","timeZone":"Europe/Berlin","validFrom":"1970-01-01T00:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1019","names":{"DE":{"name":"Calau (Niederlausitz)"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"6","postalCode":"03205","city":"Calau ","state":"Brandenburg","country":"DE"},"stationCategory":"CATEGORY_4","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"BB","timeZone":"Europe/Berlin","position":{"longitude":13.97982,"latitude":51.738118},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"102","names":{"DE":{"name":"Altenhasungen"}},"metropolis":{},"address":{"street":"Hardtstraße","postalCode":"34466","city":"Wolfhagen","state":"Hessen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB Regio-Netze","organisationalUnit":{"id":1,"name":"Kurhessenbahn (KHB)","nameShort":"KHB"}},"countryCode":"DE","state":"HE","timeZone":"Europe/Berlin","validFrom":"1970-01-01T00:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1020","names":{"DE":{"name":"Calbe (Saale) Ost"}},"metropolis":{},"address":{"street":"Am Klärwerk","postalCode":"39240","city":"Calbe (Saale)","state":"Sachsen-Anhalt","country":"DE"},"stationCategory":"CATEGORY_5","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":2,"name":"RB Südost","nameShort":"RB Südost"}},"countryCode":"DE","state":"ST","timeZone":"Europe/Berlin","position":{"longitude":11.810527,"latitude":51.920693},"validFrom":"2019-12-31T23:00:00Z"},{"stationID":"1021","names":{"DE":{"name":"Calbe (Saale) West"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"1","postalCode":"39240","city":"Calbe (Saale)","state":"Sachsen-Anhalt","country":"DE"},"stationCategory":"CATEGORY_7","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":2,"name":"RB Südost","nameShort":"RB Südost"}},"countryCode":"DE","state":"ST","timeZone":"Europe/Berlin","position":{"longitude":11.758783,"latitude":51.905693},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1022","names":{"DE":{"name":"Calberlah"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"33","postalCode":"38547","city":"Calberlah","state":"Niedersachsen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"NI","timeZone":"Europe/Berlin","position":{"longitude":10.624914,"latitude":52.427559},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1023","names":{"DE":{"name":"Caldern"}},"metropolis":{},"address":{"street":"Zum Wollenberg","postalCode":"35094","city":"Lahntal","state":"Hessen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB Regio-Netze","organisationalUnit":{"id":1,"name":"Kurhessenbahn (KHB)","nameShort":"KHB"}},"countryCode":"DE","state":"HE","timeZone":"Europe/Berlin","validFrom":"1970-01-01T00:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1025","names":{"DE":{"name":"Calw"}},"metropolis":{},"address":{"street":"Bischofstr.","houseNumber":"10","postalCode":"75365","city":"Calw","state":"Baden-Württemberg","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":6,"name":"RB Südwest","nameShort":"RB Südwest"}},"countryCode":"DE","state":"BW","timeZone":"Europe/Berlin","position":{"longitude":8.741854,"latitude":48.714682},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1026","names":{"DE":{"name":"Camburg (Saale)"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"12","postalCode":"07774","city":"Camburg (Saale)","state":"Thüringen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":2,"name":"RB Südost","nameShort":"RB Südost"}},"countryCode":"DE","state":"TH","timeZone":"Europe/Berlin","position":{"longitude":11.70468,"latitude":51.050857},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1027","names":{"DE":{"name":"Cammin (Meckl)"}},"metropolis":{},"address":{"street":"Am Bahnhof","postalCode":"17094","city":"Cammin (Meckl)","state":"Mecklenburg-Vorpommern","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"MV","timeZone":"Europe/Berlin","position":{"longitude":13.30198,"latitude":53.440365},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1028","names":{"DE":{"name":"Capelle (Westf)"}},"metropolis":{},"address":{"street":"Am Bahnhof","houseNumber":"7","postalCode":"59394","city":"Nordkirchen-Capelle","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":7.61108,"latitude":51.735268},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1029","names":{"DE":{"name":"Caputh-Geltow"}},"metropolis":{},"address":{"street":"Am Bahnhof","postalCode":"14548","city":"Schwielowsee OT Caputh","state":"Brandenburg","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"BB","timeZone":"Europe/Berlin","position":{"longitude":12.984406,"latitude":52.350295},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1032","names":{"DE":{"name":"Casekow"}},"metropolis":{},"address":{"street":"Bahnhofstraße","houseNumber":"10","postalCode":"16306","city":"Casekow","state":"Brandenburg","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":1,"name":"RB Ost","nameShort":"RB Ost"}},"countryCode":"DE","state":"BB","timeZone":"Europe/Berlin","position":{"longitude":14.208187,"latitude":53.213614},"validFrom":"2019-12-31T23:00:00Z"},{"stationID":"1033","names":{"DE":{"name":"Castrop-Rauxel Hbf"}},"metropolis":{},"address":{"street":"Berliner Platz","houseNumber":"9","postalCode":"44579","city":"Castrop-Rauxel","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_3","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":7.30398,"latitude":51.573526},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1034","names":{"DE":{"name":"Castrop-Rauxel Süd"}},"metropolis":{},"address":{"street":"Münsterplatz","houseNumber":"8","postalCode":"44575","city":"Castrop-Rauxel","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":7.310186,"latitude":51.5503},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1035","names":{"DE":{"name":"Castrop-Rauxel-Merklinde"}},"metropolis":{},"address":{"street":"Hellweg","houseNumber":"228","postalCode":"44579","city":"Castrop-Rauxel","state":"Nordrhein-Westfalen","country":"DE"},"stationCategory":"CATEGORY_6","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":4,"name":"RB West","nameShort":"RB West"}},"countryCode":"DE","state":"NW","timeZone":"Europe/Berlin","position":{"longitude":7.324314,"latitude":51.527932},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"1036","names":{"DE":{"name":"Celle Pbf"}},"metropolis":{},"address":{"street":"Bahnhofsplatz","houseNumber":"6","postalCode":"29221","city":"Celle","state":"Niedersachsen","country":"DE"},"stationCategory":"CATEGORY_3","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":3,"name":"RB Nord","nameShort":"RB Nord"}},"countryCode":"DE","state":"NI","timeZone":"Europe/Berlin","position":{"longitude":10.062468,"latitude":52.6204548},"validFrom":"2018-12-31T23:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1037","names":{"DE":{"name":"Cham (Oberpf)"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"11","postalCode":"93413","city":"Cham ","state":"Bayern","country":"DE"},"stationCategory":"CATEGORY_4","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":7,"name":"RB Süd","nameShort":"RB Süd"}},"countryCode":"DE","state":"BY","timeZone":"Europe/Berlin","position":{"longitude":12.656832,"latitude":49.221869},"validFrom":"2018-12-31T23:00:00Z","mobilityServiceStaffOnSite":false},{"stationID":"1038","names":{"DE":{"name":"Chamerau"}},"metropolis":{},"address":{"street":"Bahnhofstr.","houseNumber":"2","postalCode":"93466","city":"Chamerau","state":"Bayern","country":"DE"},"stationCategory":"CATEGORY_7","availableTransports":[],"availableLocalServices":[],"transportAssociations":[],"owner":{"name":"DB InfraGO Personenbahnhöfe","organisationalUnit":{"id":7,"name":"RB Süd","nameShort":"RB Süd"}},"countryCode":"DE","state":"BY","timeZone":"Europe/Berlin","position":{"longitude":12.745258,"latitude":49.196718},"validFrom":"2018-12-31T23:00:00Z"},{"stationID":"104","names":{"DE":{"name":"Lennestadt-Altenhundem"}},"metropolis":{},"

Testing stop-places accesspoint

In [12]:
response = requests.get(url=f"{STOP_PLACES_URL}/by-name/Warsaw?sortBy=RELEVANCE&onlyActive=true&withSynonyms=true&limit=3", headers=header_ris)
response.text

'{"stopPlaces":[{"evaNumber":"5100065","groupMembers":[],"names":{"DE":{"nameLong":"Warszawa Centralna","synonyms":[]}},"replacementTransportsAvailable":false,"availableTransports":["INTERCITY_TRAIN","INTER_REGIONAL_TRAIN"],"position":{"longitude":21.003234,"latitude":52.22886}},{"evaNumber":"5100067","groupMembers":[],"names":{"DE":{"nameLong":"Warszawa Zachodnia","synonyms":[]}},"replacementTransportsAvailable":false,"availableTransports":["INTERCITY_TRAIN","INTER_REGIONAL_TRAIN"],"position":{"longitude":20.965247,"latitude":52.219972}},{"evaNumber":"5100066","groupMembers":[],"names":{"DE":{"nameLong":"Warszawa Wschodnia","synonyms":[]}},"replacementTransportsAvailable":false,"availableTransports":["INTERCITY_TRAIN","INTER_REGIONAL_TRAIN"],"position":{"longitude":21.052335,"latitude":52.251548}}]}'

Using RIS:stations retrieve all cities main stations

In [13]:
def get_stations_api_stop_places(cities : pd.DataFrame, 
                      base_url: str = STOP_PLACES_URL,  
                      limit: int = 3) -> pd.DataFrame:
    """
    Retrieves station information from the Deutsche Bahn API based on the station name.
    
    Keyword arguments:
    cities -- DataFrame containing city information
    base_url -- Base URL for the API
    limit -- Maximum number of stations to retrieve per city
    Return: DataFrame of stations for given cities
    """
    retrieved_stations = pd.DataFrame(columns=['city_name', 'eva_id', 'station_name', 'latitude', 'longitude'])
    for _, row in cities.iterrows():
        city_name = row['name']
        response = None
        params = {
            "sortBy": "RELEVANCE",
            "onlyActive": "true",
            "withSynonyms": "true",
            "latitude": row['latitude'],
            "longitude": row['longitude'],
            "limit": limit
        }
        success = False
        retries = 0

        while not success and retries < 3:
            response = requests.get(url=f"{base_url}/by-name/{city_name}", params=params, headers=header_ris)

            if response.status_code == 429:
                print(f"Rate limit reached. Sleeping for 1s...")
                time.sleep(1)
                retries += 1
                continue

            if response.status_code == 200:
                stations = response.json().get('stopPlaces', [])
                print(f"City: {city_name}, Stations Found: {len(stations)}")
                for station in stations:
                    latitude = float(station.get('position').get('latitude'))
                    longitude = float(station.get('position').get('longitude'))

                    if haversine(row['latitude'], row['longitude'], latitude, longitude) > 10:
                        print(f"Skipping station {station.get('names').get('DE').get('nameLong')} due to distance.")
                        continue

                    retrieved_stations = pd.concat([retrieved_stations, pd.DataFrame({
                        'city_name': [city_name],
                        'eva_id': [str(station.get('evaNumber'))],
                        'station_name': [str(station.get('names').get('DE').get('nameLong'))],
                        'latitude': [float(station.get('position').get('latitude'))],
                        'longitude': [float(station.get('position').get('longitude'))]
                    })])
                success = True
            else:
                print(f"Error retrieving stations for city {city_name}: {response.status_code}")
                break

            time.sleep(0.09)  # To respect API rate limits

    return retrieved_stations

In [14]:
test_cities = cities_data.iloc[np.random.choice(cities_data.shape[0], 5, replace=False)]
test_cities

          name  latitude  longitude iso_code  population  is_capital
59  Bratislava   48.1439    17.1097       SK    475503.0        True
49      Warsaw   52.2300    21.0111       PL   1860281.0        True
17    Hannover   52.3667     9.7167       DE    545045.0       False
44        Riga   56.9489    24.1064       LV    660187.0        True
42     Vilnius   54.6872    25.2800       LT    581475.0        True

In [15]:
output  = get_stations_api_stop_places(test_cities, limit=3)

City: Bratislava, Stations Found: 3

/var/folders/pj/dyqj7jwx6r76zl2c1w7dvc7h0000gn/T/ipykernel_9906/3370103374.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  retrieved_stations = pd.concat([retrieved_stations, pd.DataFrame({

City: Warsaw, Stations Found: 3
City: Hannover, Stations Found: 3
City: Riga, Stations Found: 3
Skipping station Küssnacht am Rigi due to distance.
Skipping station Bad Godesberg Rigal'sche Wiese, Bonn due to distance.
Skipping station Rigaer Straße, Rostock due to distance.
City: Vilnius, Stations Found: 1
Skipping station Vilniuser Straße, Erfurt due to distance.

For cities above 500K we select at least 3 station if possible as timetables for those stations might contain most crutial connections

In [16]:
cities_stations = get_stations_api_stop_places(cities_data, limit=1)

City: Vienna, Stations Found: 1

/var/folders/pj/dyqj7jwx6r76zl2c1w7dvc7h0000gn/T/ipykernel_9906/3370103374.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  retrieved_stations = pd.concat([retrieved_stations, pd.DataFrame({

City: Brussels, Stations Found: 1
City: Antwerp, Stations Found: 1
City: Sofia, Stations Found: 1
Skipping station Sofie-Hammer-Straße, Osnabrück due to distance.
City: Prague, Stations Found: 1
City: Berlin, Stations Found: 1
City: Stuttgart, Stations Found: 1
City: Munich, Stations Found: 1
City: Hamburg, Stations Found: 1
City: Cologne, Stations Found: 1
City: Frankfurt, Stations Found: 1
City: Düsseldorf, Stations Found: 1
City: Leipzig, Stations Found: 1
City: Dortmund, Stations Found: 1
City: Essen, Stations Found: 1
City: Bremen, Stations Found: 1
City: Dresden, Stations Found: 1
City: Hannover, Stations Found: 1
City: Nuremberg, Stations Found: 1
City: Duisburg, Stations Found: 1
City: Copenhagen, Stations Found: 1
City: Tallinn, Stations Found: 1
Skipping station Tallinner Straße, Schwerin (Meckl) due to distance.
City: Madrid, Stations Found: 1
Skipping station Madrider Ring, Würzburg due to distance.
City: Barcelona, Stations Found: 1
City: Valencia, Stations Found: 1
Skipping station Valence TGV Rhône-Alpes Sud due to distance.
City: Sevilla, Stations Found: 0
City: Málaga, Stations Found: 0
City: Zaragoza, Stations Found: 0
City: Helsinki, Stations Found: 1
Skipping station Helsinkier Straße, Rostock due to distance.
City: Paris, Stations Found: 1
City: Bordeaux, Stations Found: 1
City: Marseille, Stations Found: 1
City: Lyon, Stations Found: 1
City: Toulouse, Stations Found: 1
City: Athens, Stations Found: 1
Skipping station Athus due to distance.
City: Zagreb, Stations Found: 1
City: Budapest, Stations Found: 1
City: Rome, Stations Found: 1
City: Milan, Stations Found: 1
City: Naples, Stations Found: 0
City: Turin, Stations Found: 1
City: Genoa, Stations Found: 1
City: Vilnius, Stations Found: 1
Skipping station Vilniuser Straße, Erfurt due to distance.
City: Luxembourg, Stations Found: 1
City: Riga, Stations Found: 1
Skipping station Küssnacht am Rigi due to distance.
City: Tilburg, Stations Found: 1
City: Amsterdam, Stations Found: 1
City: Rotterdam, Stations Found: 1
City: The Hague, Stations Found: 0
City: Warsaw, Stations Found: 1
City: Kraków, Stations Found: 1
City: Wrocław, Stations Found: 1
City: Łódź, Stations Found: 0
City: Poznań, Stations Found: 1
City: Lisbon, Stations Found: 1
Skipping station Lison(F) due to distance.
City: Bucharest, Stations Found: 0
City: Stockholm, Stations Found: 1
City: Gothenburg, Stations Found: 0
City: Ljubljana, Stations Found: 1
City: Bratislava, Stations Found: 1

In [17]:
cities_stations

    city_name   eva_id             station_name   latitude  longitude
0      Vienna  8103000                 Wien Hbf  48.185101  16.377113
0    Brussels  8800004           Bruxelles Midi  50.835376   4.335694
0     Antwerp  8800007       Antwerpen Centraal  51.215811   4.421168
0      Prague  5400014              Praha hl.n.  50.083062  14.436039
0      Berlin  8011160               Berlin Hbf  52.525592  13.369545
0   Stuttgart  8000096            Stuttgart Hbf  48.784780   9.182757
0      Munich  8000261              München Hbf  48.140232  11.558335
0     Hamburg  8002549              Hamburg Hbf  53.552736  10.006909
0     Cologne  8003368         Köln Messe/Deutz  50.940874   6.975001
0   Frankfurt  8000105       Frankfurt(Main)Hbf  50.106682   8.662828
0  Düsseldorf  8000085           Düsseldorf Hbf  51.219962   6.794319
0     Leipzig  8010205              Leipzig Hbf  51.345471  12.382064
0    Dortmund  8000080             Dortmund Hbf  51.517896   7.459290
0       Essen  8000098                Essen Hbf  51.451355   7.014793
0      Bremen  8000050               Bremen Hbf  53.083481   8.813834
0     Dresden  8010085              Dresden Hbf  51.040563  13.732035
0    Hannover  8000152             Hannover Hbf  52.376761   9.741021
0   Nuremberg  8000284             Nürnberg Hbf  49.445616  11.082989
0    Duisburg  8000086             Duisburg Hbf  51.429785   6.775903
0  Copenhagen  8601242  Koebenhavns Lufthavn st  55.629605  12.649382
0   Barcelona  7100064          Barcelona Sants  41.378914   2.140369
0       Paris  8700012       Paris Gare de Lyon  48.844841   2.374072
0    Bordeaux  8700047         Bordeaux-St-Jean  44.826486  -0.555920
0   Marseille  8700074     Marseille-St-Charles  43.303812   5.381950
0        Lyon  8700152           Lyon Part Dieu  45.760564   4.859990
0    Toulouse  8700065        Toulouse-Matabiau  43.611406   1.453939
0      Zagreb  7800020   Zagreb Glavni kolodvor  45.804438  15.978705
0    Budapest  5500728         Budapest-Nyugati  47.510706  19.057466
0        Rome  8300262           Roma Tiburtina  41.911070  12.531460
0       Milan  8300047   Milano Porta Garibaldi  45.484437   9.187297
0       Turin  8300522        Torino Porta Susa  45.071833   7.665169
0       Genoa  8300153   Genova Piazza Principe  44.417504   8.922075
0  Luxembourg  8200100               Luxembourg  49.599714   6.134396
0     Tilburg  8400597                  Tilburg  51.560610   5.083787
0   Amsterdam  8400058       Amsterdam Centraal  52.379190   4.899431
0   Rotterdam  8400530       Rotterdam Centraal  51.924802   4.468769
0      Warsaw  5100065       Warszawa Centralna  52.228860  21.003234
0      Kraków  5100028            Krakow Glowny  50.067194  19.947426
0     Wrocław  5100069           Wroclaw Glowny  51.098078  17.037088
0      Poznań  5100081            Poznan Glowny  52.401993  16.910870
0   Stockholm  7400002        Stockholm Central  59.330014  18.057630
0   Ljubljana  7900003                Ljubljana  46.058691  14.512937
0  Bratislava  5600207        Bratislava hl.st.  48.158910  17.106466

In [18]:
cities_stations[cities_stations['city_name'] == "Prague" ]

  city_name   eva_id station_name   latitude  longitude
0    Prague  5400014  Praha hl.n.  50.083062  14.436039

Found Train Stations for given cities

first cities which had no stations at DB API

In [19]:
cities_no_station = pd.merge(cities_data, cities_stations, how='outer',left_on=['name'], right_on=['city_name'], indicator=True).query('_merge == "left_only"')
cities_no_station.reset_index(inplace=True)
cities_no_station

,index,name,latitude_x,longitude_x,iso_code,population,is_capital,city_name,eva_id,station_name,latitude_y,longitude_y,_merge
0,2,Athens,37.9842,23.7281,GR,643452.0,True,NaN,NaN,NaN,NaN,NaN,left_only
1,9,Bucharest,44.4325,26.1039,RO,1716961.0,True,NaN,NaN,NaN,NaN,NaN,left_only
2,20,Gothenburg,57.7075,11.9675,SE,607882.0,False,NaN,NaN,NaN,NaN,NaN,left_only
3,23,Helsinki,60.1708,24.9375,FI,664921.0,True,NaN,NaN,NaN,NaN,NaN,left_only
4,26,Lisbon,38.7253,-9.1500,PT,548703.0,True,NaN,NaN,NaN,NaN,NaN,left_only
5,30,Madrid,40.4169,-3.7033,ES,3266126.0,True,NaN,NaN,NaN,NaN,NaN,left_only
6,34,Málaga,36.7194,-4.4200,ES,586384.0,False,NaN,NaN,NaN,NaN,NaN,left_only
7,35,Naples,40.8333,14.2500,IT,913462.0,False,NaN,NaN,NaN,NaN,NaN,left_only
8,40,Riga,56.9489,24.1064,LV,660187.0,True,NaN,NaN,NaN,NaN,NaN,left_only
9,43,Sevilla,37.3900,-5.9900,ES,684025.0,False,NaN,NaN,NaN,NaN,NaN,left_only
10,44,Sofia,42.7000,23.3300,BG,1383435.0,True,NaN,NaN,NaN,NaN,NaN,left_only
11,47,Tallinn,59.4372,24.7453,EE,461346.0,True,NaN,NaN,NaN,NaN,NaN,left_only
12,48,The Hague,52.0800,4.3100,NL,548320.0,True,NaN,NaN,NaN,NaN,NaN,left_only
13,52,Valencia,39.4700,-0.3764,ES,807693.0,False,NaN,NaN,NaN,NaN,NaN,left_only
14,54,Vilnius,54.6872,25.2800,LT,581475.0,True,NaN,NaN,NaN,NaN,NaN,left_only
15,58,Zaragoza,41.6500,-0.8833,ES,682513.0,False,NaN,NaN,NaN,NaN,NaN,left_only
16,59,Łódź,51.7769,19.4547,PL,670642.0,False,NaN,NaN,NaN,NaN,NaN,left_only

In [20]:
cities_with_stations = pd.merge(cities_data, cities_stations, how='inner',left_on=['name'], right_on=['city_name'])
cities_with_stations

,name,latitude_x,longitude_x,iso_code,population,is_capital,city_name,eva_id,station_name,latitude_y,longitude_y
0,Vienna,48.2083,16.3725,AT,1973403.0,True,Vienna,8103000,Wien Hbf,48.185101,16.377113
1,Brussels,50.8467,4.3525,BE,1235192.0,True,Brussels,8800004,Bruxelles Midi,50.835376,4.335694
2,Antwerp,51.2178,4.4003,BE,536079.0,False,Antwerp,8800007,Antwerpen Centraal,51.215811,4.421168
3,Prague,50.0875,14.4214,CZ,1357326.0,True,Prague,5400014,Praha hl.n.,50.083062,14.436039
4,Berlin,52.5200,13.4050,DE,3755251.0,True,Berlin,8011160,Berlin Hbf,52.525592,13.369545
5,Stuttgart,48.7775,9.1800,DE,632865.0,False,Stuttgart,8000096,Stuttgart Hbf,48.784780,9.182757
6,Munich,48.1375,11.5750,DE,1512491.0,False,Munich,8000261,München Hbf,48.140232,11.558335
7,Hamburg,53.5500,10.0000,DE,1892122.0,False,Hamburg,8002549,Hamburg Hbf,53.552736,10.006909
8,Cologne,50.9364,6.9528,DE,1084831.0,False,Cologne,8003368,Köln Messe/Deutz,50.940874,6.975001
9,Frankfurt,50.1106,8.6822,DE,773068.0,False,Frankfurt,8000105,Frankfurt(Main)Hbf,50.106682,8.662828
10,Düsseldorf,51.2333,6.7833,DE,629047.0,False,Düsseldorf,8000085,Düsseldorf Hbf,51.219962,6.794319
11,Leipzig,51.3400,12.3750,DE,616093.0,False,Leipzig,8010205,Leipzig Hbf,51.345471,12.382064
12,Dortmund,51.5139,7.4653,DE,593317.0,False,Dortmund,8000080,Dortmund Hbf,51.517896,7.459290
13,Essen,51.4508,7.0131,DE,584580.0,False,Essen,8000098,Essen Hbf,51.451355,7.014793
14,Bremen,53.0758,8.8072,DE,569396.0,False,Bremen,8000050,Bremen Hbf,53.083481,8.813834
15,Dresden,51.0500,13.7400,DE,563311.0,False,Dresden,8010085,Dresden Hbf,51.040563,13.732035
16,Hannover,52.3667,9.7167,DE,545045.0,False,Hannover,8000152,Hannover Hbf,52.376761,9.741021
17,Nuremberg,49.4539,11.0775,DE,523026.0,False,Nuremberg,8000284,Nürnberg Hbf,49.445616,11.082989
18,Duisburg,51.4347,6.7625,DE,502211.0,False,Duisburg,8000086,Duisburg Hbf,51.429785,6.775903
19,Copenhagen,55.6761,12.5683,DK,660842.0,True,Copenhagen,8601242,Koebenhavns Lufthavn st,55.629605,12.649382
20,Barcelona,41.3828,2.1769,ES,1620343.0,False,Barcelona,7100064,Barcelona Sants,41.378914,2.140369
21,Paris,48.8567,2.3522,FR,2148271.0,True,Paris,8700012,Paris Gare de Lyon,48.844841,2.374072
22,Bordeaux,44.8400,-0.5800,FR,994920.0,False,Bordeaux,8700047,Bordeaux-St-Jean,44.826486,-0.555920
23,Marseille,43.2964,5.3700,FR,873076.0,False,Marseille,8700074,Marseille-St-Charles,43.303812,5.381950
24,Lyon,45.7600,4.8400,FR,522250.0,False,Lyon,8700152,Lyon Part Dieu,45.760564,4.859990
25,Toulouse,43.6045,1.4440,FR,504078.0,False,Toulouse,8700065,Toulouse-Matabiau,43.611406,1.453939
26,Zagreb,45.8131,15.9775,HR,767131.0,True,Zagreb,7800020,Zagreb Glavni kolodvor,45.804438,15.978705
27,Budapest,47.4925,19.0514,HU,1671004.0,True,Budapest,5500728,Budapest-Nyugati,47.510706,19.057466
28,Rome,41.8933,12.4828,IT,2748109.0,True,Rome,8300262,Roma Tiburtina,41.911070,12.531460
29,Milan,45.4669,9.1900,IT,1354196.0,False,Milan,8300047,Milano Porta Garibaldi,45.484437,9.187297
30,Turin,45.0792,7.6761,IT,841600.0,False,Turin,8300522,Torino Porta Susa,45.071833,7.665169
31,Genoa,44.4111,8.9328,IT,558745.0,False,Genoa,8300153,Genova Piazza Principe,44.417504,8.922075
32,Luxembourg,49.6117,6.1319,LU,132780.0,True,Luxembourg,8200100,Luxembourg,49.599714,6.134396
33,Tilburg,51.5500,5.0833,NL,1944588.0,False,Tilburg,8400597,Tilburg,51.560610,5.083787
34,Amsterdam,52.3728,4.8936,NL,917923.0,True,Amsterdam,8400058,Amsterdam Centraal,52.379190,4.899431
35,Rotterdam,51.9200,4.4800,NL,664311.0,False,Rotterdam,8400530,Rotterdam Centraal,51.924802,4.468769
36,Warsaw,52.2300,21.0111,PL,1860281.0,True,Warsaw,5100065,Warszawa Centralna,52.228860,21.003234
37,Kraków,50.0614,19.9372,PL,804237.0,False,Kraków,5100028,Krakow Glowny,50.067194,19.947426
38,Wrocław,51.1100,17.0325,PL,672929.0,False,Wrocław,5100069,Wroclaw Glowny,51.098078,17.037088
39,Poznań,52.4083,16.9336,PL,546859.0,False,Poznań,5100081,Poznan Glowny,52.401993,16.910870
40,Stockholm,59.3294,18.0686,SE,984748.0,True,Stockholm,7400002,Stockholm Central,59.330014,18.057630
41,Ljubljana,46.0514,14.5061,SI,284293.0,True,Ljubljana,7900003,Ljubljana,46.058691,14.512937
42,Bratislava,48.1439,17.1097,SK,475503.0,True,Bratislava,5600207,Bratislava hl.st.,48.158910,17.106466

# Rertieve Timetables for existing city stations

currently timetables for DB offers limited data. Other timetables are required to be used

In [122]:
header_timetables = {
    "DB-Client-Id": DB_CLIENT_ID,
    "DB-Api-Key": DB_API_KEY,
    "accept": "application/xml"
}


def fetch_hourly_plan(eva_no, date_str, hour_str):
    """
    Fetches the planned timetable for a specific station, date (YYMMDD), and hour (HH).
    """
    url = f"{TIMETABLES_V1_URL}/plan/{eva_no}/{date_str}/{hour_str}"
    success = False
    rertries = 0
    plan_hour = ""

    
    while not success and rertries < 3:
        response = requests.get(url, headers=header_timetables)
        status_code  = response.status_code

        if status_code == 200:
            success = True
            retries = 0
            plan_hour =  response.text
        elif status_code == 404 or status_code == 401:
            print("Access Error: Check API")
            break 
        elif status_code == 429:
            time.sleep(1)
        retries += 1
            
    return plan_hour

def parse_hour_plan(hour_xml:str):
    pass

# test run 
fetch_hourly_plan("8103000","251229","12")

'<?xml version=\'1.0\' encoding=\'UTF-8\'?><timetable station=\'Wien Hbf\'><s id="-641886370829105986-2512291130-3"><tl f="F" t="p" o="81" c="EC" n="204"/><ar pt="2512291158" pp="12A-B" fb="EC 204" ppth="Wien Westbahnhof|Wien Meidling"/><dp pt="2512291210" pp="12A-B" fb="EC 204" pde="Krakow Glowny" ppth="Breclav|Hodonin|Stare Mesto u Uherského Hradiste|Otrokovice|Prerov|Hranice na Morave|Ostrava-Svinov|Ostrava hl.n.|Bohumin"/></s><s id="-721807130937592434-2512291213-1"><tl f="F" t="p" o="81" c="ICE" n="90"/><dp pt="2512291213" pp="8A-B" fb="ICE 90" ppth="Wien Meidling|St.Pölten Hbf|Linz Hbf|Passau Hbf|Plattling|Regensburg Hbf|Nürnberg Hbf|Coburg|Erfurt Hbf|Leipzig Hbf|Lutherstadt Wittenberg Hbf|Berlin Südkreuz|Berlin Hbf|Berlin Gesundbrunnen"/></s><s id="-6130228582536441801-2512290618-10"><tl f="F" t="p" o="51" c="EC" n="203"/><ar pt="2512291149" pp="6A-B" fb="EC 203" pde="Krakow Glowny" ppth="Bohumin|Ostrava hl.n.|Ostrava-Svinov|Hranice na Morave|Prerov|Otrokovice|Stare Mesto u Uherského Hradiste|Hodonin|Breclav"/><dp pt="2512291200" pp="6A-B" fb="EC 203" ppth="Wien Meidling|Wien Westbahnhof"/></s><s id="8366928577873353252-2512291253-1"><tl t="p" o="81" c="RJX" n="135"/><dp pt="2512291253" pp="7A-B" fb="RJX 135" ppth="Wien Meidling|Bruck/Mur|Graz Hbf|Klagenfurt Hbf|Villach Hbf|Tarvisio Boscoverde|Udine|Pordenone|Treviso Centrale|Venezia Mestre|Venezia Santa Lucia"/></s><s id="-4294777343974740944-2512291200-3"><tl f="F" t="p" o="81" c="EC" n="145"/><ar pt="2512291228" pp="12A-B" fb="EC 145" ppth="Wien Westbahnhof|Wien Meidling"/><dp pt="2512291240" pp="12A-B" fb="EC 145" ppth="Hegyeshalom|Mosonmagyarovar|Györ|Tatabanya|Budapest-Kelenföld|Budapest-Keleti"/></s><s id="-7211656151168020040-2512291113-11"><tl t="p" o="810028" c="REX" n="7617"/><ar pt="2512291237" pp="" l="6" fb="REX 6" wings="2374342303347455903-2512291113" tra="-1854652562502428523-2512291113-1" ppth="Deutschkreutz|Sopron|Baumgarten-Schattendorf|Draßburg|Wulkaprodersdorf|Müllendorf|Neufeld/Leitha|Ebenfurth|Ebreichsdorf|Wien Meidling"/></s><s id="-5810233958110953825-2512290619-12"><tl f="F" t="p" o="80" c="ICE" n="21"/><ar pt="2512291247" pp="9A-B" fb="ICE 21" ppth="Frankfurt(Main)Hbf|Hanau Hbf|Aschaffenburg Hbf|Würzburg Hbf|Nürnberg Hbf|Regensburg Hbf|Plattling|Passau Hbf|Linz Hbf|St.Pölten Hbf|Wien Meidling"/></s><s id="-869405609752317659-2512290940-7"><tl t="p" o="55" c="RJX" n="62"/><ar pt="2512291220" pp="8" fb="RJX 62" ppth="Budapest-Keleti|Budapest-Kelenföld|Tatabanya|Györ|Mosonmagyarovar|Hegyeshalom"/><dp pt="2512291228" pp="8" fb="RJX 62" ppth="Wien Meidling|St.Pölten Hbf|Linz Hbf|Salzburg Hbf|Freilassing|Traunstein|München Hbf Gl.5-10"/></s><s id="2374342303347455903-2512291113-11"><tl t="p" o="81" c="REX" n="7733"/><ar pt="2512291237" pp="11A-B" l="6" fb="REX 6" ppth="Deutschkreutz|Sopron|Baumgarten-Schattendorf|Draßburg|Wulkaprodersdorf|Müllendorf|Neufeld/Leitha|Ebenfurth|Ebreichsdorf|Wien Meidling"/><dp pt="2512291245" pp="11A-B" l="6" fb="REX 6" ppth="Wien Grillgasse|Gramatneusiedl|Bruck/Leitha|Parndorf Ort|Parndorf|Neudorf b.Parndorf|Gattendorf|Pama|Kittsee|Bratislava-Petrzalka"/></s><s id="-503434688916906956-2512290837-6"><tl t="p" o="54" c="RJ" n="55"/><ar pt="2512291249" pp="6A-B" fb="RJ 55" ppth="Praha hl.n.|Pardubice hl.n.|Ceska Trebova|Brno hl.n.|Breclav"/></s><s id="4711457516375544679-2512291150-9"><tl t="p" o="56" c="REX" n="2515"/><ar pt="2512291246" pp="5C-E" l="8" fb="REX 8" ppth="Bratislava hl.st.|Devinska Nova Ves|Marchegg|Schönfeld-Lassee|Siebenbrunn-Leopoldsdorf|Wien Aspern Nord|Wien Stadlau|Wien Simmering"/></s><s id="-1854652562502428523-2512291113-1"><tl t="p" o="810028" c="Os" n="7617"/><dp pt="2512291245" pp="" fb="Os 7617" tra="-7211656151168020040-2512291113-11" ppth="Bratislava-Petrzalka"/></s><s id="-644230531751528983-2512291214-1"><tl t="p" o="81" c="REX" n="2516"/><dp pt="2512291214" pp="11C-E" l="8" fb="REX 8" ppth="Wien Simmering|Wien Stadlau|Wien Aspern Nord|Siebenbrunn-Leopoldsdorf|Schönfeld-Lassee|Marchegg|Devinska Nova Ves|Bratislava hl.st."/></s></timetable>'

# Using v6.db.transport.rest

In [25]:
from typing import Optional, List, Dict, Any

BASE_URL = "https://v6.db.transport.rest"
RATE_LIMIT_SLEEP = 1.0  # Seconds to sleep between requests to respect 100 req/min
MAX_RETRIES = 3

def fetch_route_raw(origin_id: str, dest_id: str, departure_dt: datetime) -> Optional[Dict]:
    """
    Helper 1: Performs the actual API request for a specific date/time.
    Handles rate limiting and retries.
    """
    params = {
        "from": origin_id,
        "to": dest_id,
        "departure": departure_dt.isoformat(),
        "results": 1,           # We just need the fastest connection for this slot
        "national": "true",     # Prefer long-distance
        "nationalExpress": "true",
        # "profile": "dbweb"      # Web profile often has better international data
    }

    attempts = 0
    while attempts < MAX_RETRIES:
        try:
            response = requests.get(f"{BASE_URL}/journeys", params=params, timeout=10)
            
            if response.status_code == 200:
                time.sleep(RATE_LIMIT_SLEEP) # Polite wait
                return response.json()
            
            elif response.status_code == 429:
                wait = 2 * (attempts + 1)
                print(f"    ⚠️ Rate limit (429). Sleeping {wait}s...")
                time.sleep(wait)
                attempts += 1
            else:
                print(f"    ❌ Error {response.status_code}")
                return None
                
        except Exception as e:
            print(f"    ❌ Request failed: {e}")
            attempts += 1
            time.sleep(1)
            
    return None

route_warsaw_berlin  = fetch_route_raw("5100065", "8011160", datetime.now())

In [ ]:
def extract_journey_metrics(journey_data: Dict) -> Optional[Dict]:
    """
    Helper 2: Parses raw JSON to extract duration, transfers, and train names.
    """
    journeys = journey_data.get('journeys', [])
    if not journeys:
        return None

    # We asked for 1 result, so take the first
    best_journey = journeys[0]
    legs = best_journey.get('legs', [])
    
    if not legs:
        return None

    # Calculate timestamps and duration
    dep_str = legs[0]['departure']
    arr_str = legs[-1]['arrival']
    t_dep = datetime.fromisoformat(dep_str)
    t_arr = datetime.fromisoformat(arr_str)
    duration_minutes = (t_arr - t_dep).total_seconds() / 60

    # Extract train names for context (e.g., "ICE 100")
    trains = [
        leg.get('line', {}).get('name', '') 
        for leg in legs 
        if leg.get('mode') == 'train'
    ]

    return {
        "departure_time": dep_str,
        "arrival_time": arr_str,
        "duration_minutes": int(duration_minutes),
        "transfers": len(legs) - 1,
        "trains": ", ".join(filter(None, trains)),
        "origin_name": legs[0]['origin']['name'],
        "destination_name": legs[-1]['destination']['name']
    }

extract_journey_metrics(route_warsaw_berlin)

{'departure_time': '2025-12-30T22:16:00+01:00',
 'arrival_time': '2025-12-31T06:14:00+01:00',
 'duration_minutes': 478,
 'transfers': 0,
 'trains': '',
 'origin_name': 'Warszawa Centralna',
 'destination_name': 'Berlin Hbf'}

In [28]:
def get_best_weekly_connection(origin_id: str, dest_id: str, start_date: datetime) -> Optional[Dict]:
    """
    Helper 3: Loops through 7 days to find the minimum duration for a pair.
    """
    best_metrics = None
    min_duration = float('inf')

    # Check the same time for the next 7 days (e.g., every morning at 08:00)
    # This accounts for weekends vs weekdays schedules
    for day_offset in range(7):
        current_date = start_date + timedelta(days=day_offset)
        print(f"  Checking {current_date.strftime('%Y-%m-%d')}...", end="\r")
        
        raw_data = fetch_route_raw(origin_id, dest_id, current_date)
        
        if raw_data:
            metrics = extract_journey_metrics(raw_data)
            if metrics:
                # Update if this day offers a faster trip
                if metrics['duration_minutes'] < min_duration:
                    min_duration = metrics['duration_minutes']
                    best_metrics = metrics
                    # Add IDs back to the dict for the final dataframe
                    best_metrics['origin_id'] = origin_id
                    best_metrics['destination_id'] = dest_id
                    best_metrics['best_day'] = current_date.strftime('%A') # e.g. "Monday"

    return best_metrics

get_best_weekly_connection("5100065", "8011160", datetime.now() - timedelta(days=7))

{'departure_time': '2025-12-23T22:16:00+01:00',
 'arrival_time': '2025-12-24T06:14:00+01:00',
 'duration_minutes': 478,
 'transfers': 0,
 'trains': '',
 'origin_name': 'Warszawa Centralna',
 'destination_name': 'Berlin Hbf',
 'origin_id': '5100065',
 'destination_id': '8011160',
 'best_day': 'Tuesday'}

In [25]:
from itertools import permutations


def get_next_representative_weekday():
    """
    Finds the next Tuesday or Wednesday. 
    Mid-week days have the most consistent 'standard' schedules.
    """
    now = datetime.now()
    # 0=Mon, 1=Tue, 2=Wed...
    days_ahead = (1 - now.weekday() + 7) % 7 # Target Tuesday
    if days_ahead == 0: days_ahead = 7 # If today is Tuesday, get next week
    
    target_date = now + timedelta(days=days_ahead)
    # Set to 08:00 AM - Peak morning traffic usually has the best connections
    return target_date.replace(hour=8, minute=0, second=0, microsecond=0)

def fetch_fastest_connection(origin_id: str, dest_id: str) -> Optional[Dict]:
    """
    Makes a SINGLE smart request to find the fastest connection.
    Retrieves 5 options and picks the minimum duration.
    """
    target_date = get_next_representative_weekday()
    
    params = {
        "from": origin_id,
        "to": dest_id,
        "departure": target_date.isoformat(),
        "results": 5,           # Get 5 options in ONE request
        "national": "true",     # Prefer High Speed
        "nationalExpress": "true",
        "transfers": 4          # Allow complex routes if they are faster
    }

    # Retry logic for stability
    for attempt in range(3):
        try:
            response = requests.get(f"{BASE_URL}/journeys", params=params, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                journeys = data.get('journeys', [])
                
                if not journeys:
                    return None

                # Optimization: Process all 5 results locally to find the minimum
                min_duration = float('inf')
                best_journey = None

                for journey in journeys:
                    if not journey.get('legs'): continue
                    
                    dep = datetime.fromisoformat(journey['legs'][0]['departure'])
                    arr = datetime.fromisoformat(journey['legs'][-1]['arrival'])
                    duration = (arr - dep).total_seconds() / 60
                    
                    if duration < min_duration:
                        min_duration = duration
                        best_journey = journey
                        best_journey['calculated_duration'] = int(duration)

                # Extract details from the winner
                legs = best_journey['legs']
                train_names = [l.get('line', {}).get('name', '') for l in legs if l.get('mode') == 'train']

                time.sleep(RATE_LIMIT_SLEEP) # Respect limits
                return {
                    "origin_id": origin_id,
                    "destination_id": dest_id,
                    "origin_name": legs[0]['origin']['name'],
                    "destination_name": legs[-1]['destination']['name'],
                    "min_duration_minutes": best_journey['calculated_duration'],
                    "transfers": len(legs) - 1,
                    "trains": ", ".join(filter(None, train_names)),
                    "check_date": target_date.strftime("%Y-%m-%d")
                }

            elif response.status_code == 429:
                time.sleep(3 * (attempt + 1)) # Backoff
            elif response.status_code >= 500:
                time.sleep(2)
            else:
                return None
                
        except Exception as e:
            time.sleep(1)

    return None

def get_efficient_network_data(eva_ids: List[str]) -> pd.DataFrame:
    """
    Main Runner.
    Reduced Complexity: O(N * (N-1)) requests instead of O(N * (N-1) * 7).
    """
    # Use permutations because A->B might be slightly different than B->A 
    # (e.g. connections matching up)
    pairs = list(permutations(eva_ids, 2))
    
    print(f"🚀 Optimized Search: {len(eva_ids)} stations -> {len(pairs)} routes.")
    print(f"📅 Using representative weekday: {get_next_representative_weekday().strftime('%A, %Y-%m-%d')}")
    
    results = []
    
    for i, (origin, dest) in enumerate(pairs):
        print(f"[{i+1}/{len(pairs)}] {origin} -> {dest}...", end=" ", flush=True)
        
        data = fetch_fastest_connection(origin, dest)
        
        if data:
            print(f"✅ {data['min_duration_minutes']} min")
            results.append(data)
        else:
            print(f"❌ No route")

    return pd.DataFrame(results)

In [26]:
routes_data = get_efficient_network_data(cities_stations['eva_id'].tolist())
routes_data

🚀 Optimized Search: 43 stations -> 1806 routes.
📅 Using representative weekday: Tuesday, 2026-01-06
[1/1806] 8103000 -> 8800004...

KeyboardInterrupt:

# Scrape API with intermittent saves to prevent data loss

In [35]:
# this code was generated by Claude (as you can tell by the comments lol)
# i went over it, fixed and added things, so it should be alright

import time

def scrape_train_routes_with_checkpoints(eva_ids: List[str], batch_size: int = 10):
    """
    Scrapes train routes and persists to CSV every batch_size API calls.
    Includes progress tracking and crash resilience.
    
    Args:
        eva_ids: List of station EVA IDs to query
        batch_size: Save to CSV after this many successful API calls (default: 10)
    """
    from itertools import permutations
    
    # Setup output file
    output_file = RAW_DATA_DIR / "train_routes_scraped.csv"
    
    # Check if file already exists to resume from where we left off
    processed_pairs = set()
    if output_file.exists():
        existing_df = pd.read_csv(output_file)
        processed_pairs = set(zip(existing_df['origin_id'], existing_df['destination_id']))
        print(f"📋 Resuming: Found {len(processed_pairs)} existing routes")
    else:
        print(f"📝 Starting fresh: Creating new output file at {output_file}")
    
    # Generate all pairs
    pairs = list(permutations(eva_ids, 2))
    pending_pairs = [p for p in pairs if p not in processed_pairs]
    
    print(f"🚀 Total routes to scrape: {len(pending_pairs)} (from {len(pairs)} possible pairs)")
    print(f"📅 Using representative weekday: {get_next_representative_weekday().strftime('%A, %Y-%m-%d')}\n")
    
    batch_results = []
    api_calls_count = 0
    failed_count = 0
    
    try:
        for idx, (origin, dest) in enumerate(pending_pairs):
            pair_num = idx + len(processed_pairs) + 1
            print(f"[{pair_num}/{len(pairs)}] {origin} → {dest}...", end=" ", flush=True)
            
            try:
                start_time = time.time()
                data = fetch_fastest_connection(origin, dest)
                elapsed = time.time() - start_time
                
                if data:
                    print(f"✅ {data['min_duration_minutes']} min (retrieved in {elapsed} seconds)")
                    batch_results.append(data)
                    api_calls_count += 1
                else:
                    print(f"⚠️  No route found (retrieved in {elapsed} seconds)")

                    # if no route was found, still add it to output dataset.
                    # this is so that the scraping does not try again for this city combination when restarted
                    data = {
                        "origin_id": origin,
                        "destination_id": dest,
                        "origin_name": "",
                        "destination_name": "",
                        "min_duration_minutes": -1,
                        "transfers": 0,
                        "trains": "",
                        "check_date": get_next_representative_weekday().strftime("%Y-%m-%d")
                    }
                    batch_results.append(data)

                    api_calls_count += 1
                    failed_count += 1
                
                # Batch save every N successful calls
                if api_calls_count >= batch_size:
                    batch_df = pd.DataFrame(batch_results)
                    
                    # Append to CSV (or create if doesn't exist)
                    if output_file.exists():
                        batch_df.to_csv(output_file, mode='a', header=False, index=False)
                    else:
                        batch_df.to_csv(output_file, mode='w', header=True, index=False)
                    
                    print(f"\n💾 Checkpoint: Saved {api_calls_count} routes to {output_file.name}")
                    
                    batch_results = []
                    api_calls_count = 0
                    
            except Exception as e:
                print(f"❌ Error: {e}")
                failed_count += 1
                time.sleep(2)  # Back off on error
                continue
        
        # Final save of remaining results
        if batch_results:
            batch_df = pd.DataFrame(batch_results)
            if output_file.exists():
                batch_df.to_csv(output_file, mode='a', header=False, index=False)
            else:
                batch_df.to_csv(output_file, mode='w', header=True, index=False)
            print(f"\n💾 Final Checkpoint: Saved {len(batch_results)} remaining routes")
        
        # Summary
        total_routes = len(processed_pairs) + len(batch_results) + api_calls_count
        print(f"\n" + "="*60)
        print(f"✨ Scraping Complete!")
        print(f"   Successful: {total_routes}")
        print(f"   Failed: {failed_count}")
        print(f"   Total pairs processed: {total_routes + failed_count}/{len(pairs)}")
        print(f"   Output file: {output_file}")
        print(f"="*60)
        
    except KeyboardInterrupt:
        print(f"\n⏸️  Interrupted by user")
        # Save any remaining batch data before exiting
        if batch_results:
            batch_df = pd.DataFrame(batch_results)
            if output_file.exists():
                batch_df.to_csv(output_file, mode='a', header=False, index=False)
            else:
                batch_df.to_csv(output_file, mode='w', header=True, index=False)
            print(f"💾 Saved {len(batch_results)} routes before exit")
        raise

In [36]:
# Start the scraping job
scrape_train_routes_with_checkpoints(cities_stations['eva_id'].tolist(), batch_size=10)

📋 Resuming: Found 273 existing routes
🚀 Total routes to scrape: 1806 (from 1806 possible pairs)
📅 Using representative weekday: Tuesday, 2026-01-06

[274/1806] 8103000 → 8800004... ✅ 622 min (retrieved in 3.0251519680023193 seconds)
[275/1806] 8103000 → 8800007... ✅ 653 min (retrieved in 3.5183348655700684 seconds)
[276/1806] 8103000 → 5400014... ✅ 253 min (retrieved in 1.4938020706176758 seconds)
[277/1806] 8103000 → 8011160... ✅ 429 min (retrieved in 1.148447036743164 seconds)
[278/1806] 8103000 → 8000096... ✅ 391 min (retrieved in 1.1549482345581055 seconds)
[279/1806] 8103000 → 8000261... ✅ 253 min (retrieved in 1.5753850936889648 seconds)
[280/1806] 8103000 → 8002549... ✅ 524 min (retrieved in 2.0647530555725098 seconds)
[281/1806] 8103000 → 8003368... ✅ 481 min (retrieved in 2.5753250122070312 seconds)
[282/1806] 8103000 → 8000105... ✅ 384 min (retrieved in 1.97574782371521 seconds)
[283/1806] 8103000 → 8000085... ✅ 499 min (retrieved in 2.96864914894104 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[284/1806] 8103000 → 8010205... ✅ 378 min (retrieved in 2.8933918476104736 seconds)
[285/1806] 8103000 → 8000080... ✅ 546 min (retrieved in 2.5995190143585205 seconds)
[286/1806] 8103000 → 8000098... ✅ 525 min (retrieved in 2.9995322227478027 seconds)
[287/1806] 8103000 → 8000050... ✅ 514 min (retrieved in 2.164400100708008 seconds)
[288/1806] 8103000 → 8010085... ✅ 400 min (retrieved in 1.7340168952941895 seconds)
[289/1806] 8103000 → 8000152... ✅ 439 min (retrieved in 2.089885950088501 seconds)
[290/1806] 8103000 → 8000284... ✅ 252 min (retrieved in 1.6962130069732666 seconds)
[291/1806] 8103000 → 8000086... ✅ 512 min (retrieved in 2.4168200492858887 seconds)
[292/1806] 8103000 → 8601242... ✅ 910 min (retrieved in 4.190258264541626 seconds)
[293/1806] 8103000 → 7100064... ✅ 1195 min (retrieved in 3.813278913497925 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[294/1806] 8103000 → 8700012... ✅ 714 min (retrieved in 3.3188531398773193 seconds)
[295/1806] 8103000 → 8700047... ✅ 1246 min (retrieved in 7.704226970672607 seconds)
[296/1806] 8103000 → 8700074... ✅ 1236 min (retrieved in 3.3998470306396484 seconds)
[297/1806] 8103000 → 8700152... ✅ 991 min (retrieved in 5.234064102172852 seconds)
[298/1806] 8103000 → 8700065... ✅ 1160 min (retrieved in 4.47995400428772 seconds)
[299/1806] 8103000 → 7800020... ✅ 421 min (retrieved in 1.6637709140777588 seconds)
[300/1806] 8103000 → 5500728... ✅ 187 min (retrieved in 1.3636159896850586 seconds)
[301/1806] 8103000 → 8300262... ✅ 691 min (retrieved in 7.170736789703369 seconds)
[302/1806] 8103000 → 8300047... ✅ 602 min (retrieved in 4.755724906921387 seconds)
[303/1806] 8103000 → 8300522... ✅ 676 min (retrieved in 4.063859939575195 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[304/1806] 8103000 → 8300153... ✅ 732 min (retrieved in 4.035340070724487 seconds)
[305/1806] 8103000 → 8200100... ✅ 637 min (retrieved in 2.490823268890381 seconds)
[306/1806] 8103000 → 8400597... ✅ 652 min (retrieved in 2.6008920669555664 seconds)
[307/1806] 8103000 → 8400058... ✅ 712 min (retrieved in 2.7218830585479736 seconds)
[308/1806] 8103000 → 8400530... ✅ 691 min (retrieved in 3.5277318954467773 seconds)
[309/1806] 8103000 → 5100065... ✅ 474 min (retrieved in 1.7542469501495361 seconds)
[310/1806] 8103000 → 5100028... ✅ 320 min (retrieved in 1.6948440074920654 seconds)
[311/1806] 8103000 → 5100069... ✅ 316 min (retrieved in 1.9448938369750977 seconds)
[312/1806] 8103000 → 5100081... ✅ 434 min (retrieved in 1.5261597633361816 seconds)
[313/1806] 8103000 → 7400002... ✅ 1303 min (retrieved in 4.225719213485718 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[314/1806] 8103000 → 7900003... ✅ 316 min (retrieved in 2.4602410793304443 seconds)
[315/1806] 8103000 → 5600207... ✅ 56 min (retrieved in 1.627614974975586 seconds)
[316/1806] 8800004 → 8103000... ✅ 622 min (retrieved in 3.3940441608428955 seconds)
[317/1806] 8800004 → 8800007... ✅ 34 min (retrieved in 1.409797191619873 seconds)
[318/1806] 8800004 → 5400014... ✅ 656 min (retrieved in 3.752452850341797 seconds)
[319/1806] 8800004 → 8011160... ✅ 390 min (retrieved in 4.2700653076171875 seconds)
[320/1806] 8800004 → 8000096... ✅ 248 min (retrieved in 2.86323881149292 seconds)
[321/1806] 8800004 → 8000261... ✅ 375 min (retrieved in 2.899688959121704 seconds)
[322/1806] 8800004 → 8002549... ✅ 349 min (retrieved in 2.3172616958618164 seconds)
[323/1806] 8800004 → 8003368... ✅ 119 min (retrieved in 2.693726062774658 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[324/1806] 8800004 → 8000105... ✅ 182 min (retrieved in 2.2160696983337402 seconds)
[325/1806] 8800004 → 8000085... ✅ 142 min (retrieved in 3.0810959339141846 seconds)
[326/1806] 8800004 → 8010205... ✅ 399 min (retrieved in 2.4340460300445557 seconds)
[327/1806] 8800004 → 8000080... ✅ 191 min (retrieved in 2.4734981060028076 seconds)
[328/1806] 8800004 → 8000098... ✅ 168 min (retrieved in 2.434891939163208 seconds)
[329/1806] 8800004 → 8000050... ✅ 325 min (retrieved in 2.5410749912261963 seconds)
[330/1806] 8800004 → 8010085... ✅ 492 min (retrieved in 3.843519926071167 seconds)
[331/1806] 8800004 → 8000152... ✅ 294 min (retrieved in 3.3476779460906982 seconds)
[332/1806] 8800004 → 8000284... ✅ 333 min (retrieved in 2.3201820850372314 seconds)
[333/1806] 8800004 → 8000086... ✅ 155 min (retrieved in 1.9716300964355469 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[334/1806] 8800004 → 8601242... ✅ 723 min (retrieved in 4.713511943817139 seconds)
[335/1806] 8800004 → 7100064... ✅ 546 min (retrieved in 4.346277952194214 seconds)
[336/1806] 8800004 → 8700012... ✅ 114 min (retrieved in 1.4997649192810059 seconds)
[337/1806] 8800004 → 8700047... ✅ 271 min (retrieved in 3.2977750301361084 seconds)
[338/1806] 8800004 → 8700074... ✅ 341 min (retrieved in 2.7465527057647705 seconds)
[339/1806] 8800004 → 8700152... ✅ 223 min (retrieved in 1.316058874130249 seconds)
[340/1806] 8800004 → 8700065... ✅ 435 min (retrieved in 1.149216890335083 seconds)
[341/1806] 8800004 → 7800020... ✅ 1088 min (retrieved in 1.1564841270446777 seconds)
[342/1806] 8800004 → 5500728... ✅ 864 min (retrieved in 1.1654369831085205 seconds)
[343/1806] 8800004 → 8300262... ✅ 778 min (retrieved in 1.165297031402588 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[344/1806] 8800004 → 8300047... ✅ 538 min (retrieved in 1.15212082862854 seconds)
[345/1806] 8800004 → 8300522... ✅ 453 min (retrieved in 1.1517601013183594 seconds)
[346/1806] 8800004 → 8300153... ✅ 588 min (retrieved in 1.1446430683135986 seconds)
[347/1806] 8800004 → 8200100... ✅ 197 min (retrieved in 1.1483583450317383 seconds)
[348/1806] 8800004 → 8400597... ✅ 110 min (retrieved in 1.1552729606628418 seconds)
[349/1806] 8800004 → 8400058... ✅ 117 min (retrieved in 1.1574170589447021 seconds)
[350/1806] 8800004 → 8400530... ✅ 69 min (retrieved in 1.15616774559021 seconds)
[351/1806] 8800004 → 5100065... ✅ 755 min (retrieved in 1.1610538959503174 seconds)
[352/1806] 8800004 → 5100028... ✅ 859 min (retrieved in 1.1527009010314941 seconds)
[353/1806] 8800004 → 5100069... ✅ 683 min (retrieved in 1.158951997756958 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[354/1806] 8800004 → 5100081... ✅ 608 min (retrieved in 1.160733938217163 seconds)
[355/1806] 8800004 → 7400002... ✅ 1171 min (retrieved in 1.1578190326690674 seconds)
[356/1806] 8800004 → 7900003... ✅ 833 min (retrieved in 1.2927091121673584 seconds)
[357/1806] 8800004 → 5600207... ✅ 705 min (retrieved in 1.3191180229187012 seconds)
[358/1806] 8800007 → 8103000... ✅ 653 min (retrieved in 1.2812817096710205 seconds)
[359/1806] 8800007 → 8800004... ✅ 33 min (retrieved in 1.2370641231536865 seconds)
[360/1806] 8800007 → 5400014... ✅ 691 min (retrieved in 1.151611089706421 seconds)
[361/1806] 8800007 → 8011160... ✅ 421 min (retrieved in 1.1843478679656982 seconds)
[362/1806] 8800007 → 8000096... ✅ 317 min (retrieved in 1.1659629344940186 seconds)
[363/1806] 8800007 → 8000261... ✅ 433 min (retrieved in 1.1838998794555664 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[364/1806] 8800007 → 8002549... ✅ 380 min (retrieved in 1.158139944076538 seconds)
[365/1806] 8800007 → 8003368... ✅ 152 min (retrieved in 1.1497650146484375 seconds)
[366/1806] 8800007 → 8000105... ✅ 213 min (retrieved in 1.158397912979126 seconds)
[367/1806] 8800007 → 8000085... ✅ 173 min (retrieved in 1.1476976871490479 seconds)
[368/1806] 8800007 → 8010205... ✅ 435 min (retrieved in 1.1686630249023438 seconds)
[369/1806] 8800007 → 8000080... ✅ 236 min (retrieved in 1.1636312007904053 seconds)
[370/1806] 8800007 → 8000098... ✅ 209 min (retrieved in 1.1559600830078125 seconds)
[371/1806] 8800007 → 8000050... ✅ 339 min (retrieved in 1.1874480247497559 seconds)
[372/1806] 8800007 → 8010085... ✅ 523 min (retrieved in 1.153749942779541 seconds)
[373/1806] 8800007 → 8000152... ✅ 325 min (retrieved in 1.1638920307159424 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[374/1806] 8800007 → 8000284... ✅ 364 min (retrieved in 1.1743547916412354 seconds)
[375/1806] 8800007 → 8000086... ✅ 189 min (retrieved in 1.1503701210021973 seconds)
[376/1806] 8800007 → 8601242... ✅ 754 min (retrieved in 1.3156230449676514 seconds)
[377/1806] 8800007 → 7100064... ✅ 590 min (retrieved in 1.2861640453338623 seconds)
[378/1806] 8800007 → 8700012... ✅ 154 min (retrieved in 1.1729090213775635 seconds)
[379/1806] 8800007 → 8700047... ✅ 313 min (retrieved in 1.3396570682525635 seconds)
[380/1806] 8800007 → 8700074... ✅ 381 min (retrieved in 1.143765926361084 seconds)
[381/1806] 8800007 → 8700152... ✅ 289 min (retrieved in 1.1657991409301758 seconds)
[382/1806] 8800007 → 8700065... ✅ 475 min (retrieved in 1.1729328632354736 seconds)
[383/1806] 8800007 → 7800020... ✅ 1145 min (retrieved in 1.157109022140503 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[384/1806] 8800007 → 5500728... ✅ 895 min (retrieved in 1.1545488834381104 seconds)
[385/1806] 8800007 → 8300262... ✅ 847 min (retrieved in 1.1549158096313477 seconds)
[386/1806] 8800007 → 8300047... ✅ 601 min (retrieved in 1.166240930557251 seconds)
[387/1806] 8800007 → 8300522... ✅ 522 min (retrieved in 1.1539452075958252 seconds)
[388/1806] 8800007 → 8300153... ✅ 657 min (retrieved in 1.1542837619781494 seconds)
[389/1806] 8800007 → 8200100... ✅ 235 min (retrieved in 1.157350778579712 seconds)
[390/1806] 8800007 → 8400597... ✅ 58 min (retrieved in 1.1608428955078125 seconds)
[391/1806] 8800007 → 8400058... ✅ 80 min (retrieved in 1.1568472385406494 seconds)
[392/1806] 8800007 → 8400530... ✅ 32 min (retrieved in 1.1563477516174316 seconds)
[393/1806] 8800007 → 5100065... ✅ 745 min (retrieved in 1.1535091400146484 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[394/1806] 8800007 → 5100028... ✅ 1020 min (retrieved in 1.1604938507080078 seconds)
[395/1806] 8800007 → 5100069... ✅ 740 min (retrieved in 1.1665611267089844 seconds)
[396/1806] 8800007 → 5100081... ✅ 598 min (retrieved in 1.3276951313018799 seconds)
[397/1806] 8800007 → 7400002... ✅ 1166 min (retrieved in 1.3357868194580078 seconds)
[398/1806] 8800007 → 7900003... ✅ 924 min (retrieved in 1.3381731510162354 seconds)
[399/1806] 8800007 → 5600207... ⚠️  No route found (retrieved in 33.521594762802124 seconds)
[400/1806] 5400014 → 8103000... ⚠️  No route found (retrieved in 33.31092190742493 seconds)
[401/1806] 5400014 → 8800004... ⚠️  No route found (retrieved in 33.3262619972229 seconds)
[402/1806] 5400014 → 8800007... ⚠️  No route found (retrieved in 33.32719898223877 seconds)
[403/1806] 5400014 → 8011160... ⚠️  No route found (retrieved in 33.33427929878235 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[404/1806] 5400014 → 8000096... ⚠️  No route found (retrieved in 33.318087100982666 seconds)
[405/1806] 5400014 → 8000261... ⚠️  No route found (retrieved in 33.32880878448486 seconds)
[406/1806] 5400014 → 8002549... ⚠️  No route found (retrieved in 33.36644411087036 seconds)
[407/1806] 5400014 → 8003368... ⚠️  No route found (retrieved in 33.315513134002686 seconds)
[408/1806] 5400014 → 8000105... ✅ 433 min (retrieved in 1.1605260372161865 seconds)
[409/1806] 5400014 → 8000085... ✅ 519 min (retrieved in 1.2017982006072998 seconds)
[410/1806] 5400014 → 8010205... ✅ 240 min (retrieved in 1.2252111434936523 seconds)
[411/1806] 5400014 → 8000080... ✅ 460 min (retrieved in 1.1567988395690918 seconds)
[412/1806] 5400014 → 8000098... ✅ 486 min (retrieved in 1.1526668071746826 seconds)
[413/1806] 5400014 → 8000050... ✅ 439 min (retrieved in 1.1579108238220215 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[414/1806] 5400014 → 8010085... ✅ 139 min (retrieved in 1.150866985321045 seconds)
[415/1806] 5400014 → 8000152... ✅ 357 min (retrieved in 1.1745989322662354 seconds)
[416/1806] 5400014 → 8000284... ✅ 280 min (retrieved in 1.1559760570526123 seconds)
[417/1806] 5400014 → 8000086... ✅ 500 min (retrieved in 1.1528429985046387 seconds)
[418/1806] 5400014 → 8601242... ✅ 892 min (retrieved in 1.183992862701416 seconds)
[419/1806] 5400014 → 7100064... ✅ 1492 min (retrieved in 1.153564214706421 seconds)
[420/1806] 5400014 → 8700012... ✅ 921 min (retrieved in 1.157824993133545 seconds)
[421/1806] 5400014 → 8700047... ✅ 1063 min (retrieved in 1.1561360359191895 seconds)
[422/1806] 5400014 → 8700074... ✅ 1123 min (retrieved in 1.1594221591949463 seconds)
[423/1806] 5400014 → 8700152... ✅ 988 min (retrieved in 1.1962740421295166 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[424/1806] 5400014 → 8700065... ✅ 1244 min (retrieved in 1.1661467552185059 seconds)
[425/1806] 5400014 → 7800020... ✅ 719 min (retrieved in 1.1608150005340576 seconds)
[426/1806] 5400014 → 5500728... ✅ 411 min (retrieved in 1.1569902896881104 seconds)
[427/1806] 5400014 → 8300262... ✅ 993 min (retrieved in 1.194305181503296 seconds)
[428/1806] 5400014 → 8300047... ✅ 868 min (retrieved in 1.1636359691619873 seconds)
[429/1806] 5400014 → 8300522... ✅ 1067 min (retrieved in 1.1557910442352295 seconds)
[430/1806] 5400014 → 8300153... ✅ 1183 min (retrieved in 1.2164020538330078 seconds)
[431/1806] 5400014 → 8200100... ✅ 674 min (retrieved in 2.874868392944336 seconds)
[432/1806] 5400014 → 8400597... ✅ 675 min (retrieved in 3.9951581954956055 seconds)
[433/1806] 5400014 → 8400058... ✅ 658 min (retrieved in 5.193397045135498 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[434/1806] 5400014 → 8400530... ✅ 669 min (retrieved in 3.7749991416931152 seconds)
[435/1806] 5400014 → 5100065... ✅ 491 min (retrieved in 1.605226993560791 seconds)
[436/1806] 5400014 → 5100028... ✅ 349 min (retrieved in 1.5046422481536865 seconds)
[437/1806] 5400014 → 5100069... ✅ 237 min (retrieved in 1.451286792755127 seconds)
[438/1806] 5400014 → 5100081... ✅ 335 min (retrieved in 1.6259121894836426 seconds)
[439/1806] 5400014 → 7400002... ✅ 1222 min (retrieved in 1.1721301078796387 seconds)
[440/1806] 5400014 → 7900003... ✅ 615 min (retrieved in 1.1642160415649414 seconds)
[441/1806] 5400014 → 5600207... ✅ 265 min (retrieved in 1.1518208980560303 seconds)
[442/1806] 8011160 → 8103000... ✅ 431 min (retrieved in 1.1526250839233398 seconds)
[443/1806] 8011160 → 8800004... ✅ 391 min (retrieved in 1.1779091358184814 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[444/1806] 8011160 → 8800007... ✅ 422 min (retrieved in 1.1701250076293945 seconds)
[445/1806] 8011160 → 5400014... ✅ 237 min (retrieved in 1.1548559665679932 seconds)
[446/1806] 8011160 → 8000096... ✅ 317 min (retrieved in 1.1537861824035645 seconds)
[447/1806] 8011160 → 8000261... ✅ 235 min (retrieved in 1.1609740257263184 seconds)
[448/1806] 8011160 → 8002549... ✅ 148 min (retrieved in 1.1566250324249268 seconds)
[449/1806] 8011160 → 8003368... ✅ 251 min (retrieved in 1.1558728218078613 seconds)
[450/1806] 8011160 → 8000105... ✅ 231 min (retrieved in 1.1554019451141357 seconds)
[451/1806] 8011160 → 8000085... ✅ 254 min (retrieved in 1.143822193145752 seconds)
[452/1806] 8011160 → 8010205... ✅ 75 min (retrieved in 1.1493420600891113 seconds)
[453/1806] 8011160 → 8000080... ✅ 204 min (retrieved in 1.1477501392364502 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[454/1806] 8011160 → 8000098... ✅ 229 min (retrieved in 1.161681890487671 seconds)
[455/1806] 8011160 → 8000050... ✅ 164 min (retrieved in 1.3052899837493896 seconds)
[456/1806] 8011160 → 8010085... ✅ 99 min (retrieved in 1.1503632068634033 seconds)
[457/1806] 8011160 → 8000152... ✅ 93 min (retrieved in 1.1520779132843018 seconds)
[458/1806] 8011160 → 8000284... ✅ 166 min (retrieved in 1.1613900661468506 seconds)
[459/1806] 8011160 → 8000086... ✅ 242 min (retrieved in 1.14487624168396 seconds)
[460/1806] 8011160 → 8601242... ✅ 500 min (retrieved in 1.192296028137207 seconds)
[461/1806] 8011160 → 7100064... ✅ 1024 min (retrieved in 1.1486868858337402 seconds)
[462/1806] 8011160 → 8700012... ✅ 531 min (retrieved in 1.1539382934570312 seconds)
[463/1806] 8011160 → 8700047... ✅ 673 min (retrieved in 1.1556050777435303 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[464/1806] 8011160 → 8700074... ✅ 730 min (retrieved in 1.1546711921691895 seconds)
[465/1806] 8011160 → 8700152... ✅ 622 min (retrieved in 1.1858899593353271 seconds)
[466/1806] 8011160 → 8700065... ✅ 1068 min (retrieved in 1.1586999893188477 seconds)
[467/1806] 8011160 → 7800020... ✅ 894 min (retrieved in 1.1547751426696777 seconds)
[468/1806] 8011160 → 5500728... ✅ 660 min (retrieved in 1.1801390647888184 seconds)
[469/1806] 8011160 → 8300262... ✅ 973 min (retrieved in 1.167320966720581 seconds)
[470/1806] 8011160 → 8300047... ✅ 722 min (retrieved in 1.1580212116241455 seconds)
[471/1806] 8011160 → 8300522... ✅ 833 min (retrieved in 1.160038948059082 seconds)
[472/1806] 8011160 → 8300153... ✅ 836 min (retrieved in 1.154613971710205 seconds)
[473/1806] 8011160 → 8200100... ✅ 499 min (retrieved in 1.158501148223877 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[474/1806] 8011160 → 8400597... ✅ 370 min (retrieved in 1.150376796722412 seconds)
[475/1806] 8011160 → 8400058... ✅ 344 min (retrieved in 1.152651071548462 seconds)
[476/1806] 8011160 → 8400530... ✅ 369 min (retrieved in 1.1596949100494385 seconds)
[477/1806] 8011160 → 5100065... ✅ 306 min (retrieved in 1.1506516933441162 seconds)
[478/1806] 8011160 → 5100028... ✅ 412 min (retrieved in 1.1515328884124756 seconds)
[479/1806] 8011160 → 5100069... ✅ 241 min (retrieved in 1.1480929851531982 seconds)
[480/1806] 8011160 → 5100081... ✅ 161 min (retrieved in 1.1821660995483398 seconds)
[481/1806] 8011160 → 7400002... ✅ 810 min (retrieved in 1.1474671363830566 seconds)
[482/1806] 8011160 → 7900003... ✅ 642 min (retrieved in 1.1582159996032715 seconds)
[483/1806] 8011160 → 5600207... ✅ 514 min (retrieved in 1.1415610313415527 seconds)

💾 Checkpoint: Saved 10 routes to train_stations_europe_scraped.csv
[484/1806] 8000096 → 8103000... ✅ 394 min (retrieved in 1.1467931270599365 seconds)
[485/1806] 8000096 → 8800004... ✅ 286 min (retrieved in 1.1502032279968262 seconds)
[486/1806] 8000096 → 8800007... ✅ 317 min (retrieved in 1.1445839405059814 seconds)
[487/1806] 8000096 → 5400014... ✅ 441 min (retrieved in 1.1531169414520264 seconds)
[488/1806] 8000096 → 8011160... ✅ 314 min (retrieved in 1.1546978950500488 seconds)
[489/1806] 8000096 → 8000261... ✅ 117 min (retrieved in 1.1685748100280762 seconds)
[490/1806] 8000096 → 8002549... ✅ 306 min (retrieved in 1.15065336227417 seconds)
[491/1806] 8000096 → 8003368... ✅ 123 min (retrieved in 1.148714303970337 seconds)
[492/1806] 8000096 → 8000105... ✅ 77 min (retrieved in 1.1486079692840576 seconds)

# Remove duplicates from saved data

In [5]:
import pandas as pd

input_file = f"{RAW_DATA_DIR}/train_routes_scraped.csv"
output_file = f"{PROCESSED_DATA_DIR}/train_routes_scraped_no_duplicates.csv"

df = pd.read_csv(input_file)

# Remove duplicate rows
df = df.drop_duplicates()

# Save result
df.to_csv(output_file, index=False)

# Add back cities to routes data

In [26]:
df_routes = pd.read_csv("Raw_Data/train_routes_scraped.csv")
df_routes.rename(columns={"origin_name": "origin_station_name", "destination_name": "destination_station_name"}, inplace=True)

cities_stations_names_only = cities_stations[["city_name", "station_name"]]

cities_stations_origin = cities_stations.add_prefix("origin_")
cities_stations_destination = cities_stations.add_prefix("destination_")

df_routes_with_city_names = df_routes.merge(cities_stations_origin, on="origin_station_name")
df_routes_with_city_names = df_routes_with_city_names.merge(cities_stations_destination, on="destination_station_name")

df_routes_with_city_names

,origin_id,destination_id,origin_station_name,destination_station_name,min_duration_minutes,transfers,trains,check_date,origin_city_name,origin_eva_id,origin_latitude,origin_longitude,destination_city_name,destination_eva_id,destination_latitude,destination_longitude
0,8103000,8000261,Wien Hbf,München Hbf,253,2,NaN,2026-01-06,Vienna,8103000,48.185101,16.377113,Munich,8000261,48.140232,11.558335
1,8103000,8002549,Wien Hbf,Hamburg Hbf,524,2,NaN,2026-01-06,Vienna,8103000,48.185101,16.377113,Hamburg,8002549,53.552736,10.006909
2,8103000,8000105,Wien Hbf,Frankfurt(Main)Hbf,384,0,NaN,2026-01-06,Vienna,8103000,48.185101,16.377113,Frankfurt,8000105,50.106682,8.662828
3,8103000,8000085,Wien Hbf,Düsseldorf Hbf,499,2,NaN,2026-01-06,Vienna,8103000,48.185101,16.377113,Düsseldorf,8000085,51.219962,6.794319
4,8103000,8010205,Wien Hbf,Leipzig Hbf,378,4,NaN,2026-01-06,Vienna,8103000,48.185101,16.377113,Leipzig,8010205,51.345471,12.382064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,5600207,5100028,Bratislava hl.st.,Krakow Glowny,350,2,NaN,2026-01-06,Bratislava,5600207,48.158910,17.106466,Kraków,5100028,50.067194,19.947426
2054,5600207,5100069,Bratislava hl.st.,Wroclaw Glowny,380,4,NaN,2026-01-06,Bratislava,5600207,48.158910,17.106466,Wrocław,5100069,51.098078,17.037088
2055,5600207,5100081,Bratislava hl.st.,Poznan Glowny,407,2,NaN,2026-01-06,Bratislava,5600207,48.158910,17.106466,Poznań,5100081,52.401993,16.910870
2056,5600207,7400002,Bratislava hl.st.,Stockholm Central,1386,6,NaN,2026-01-06,Bratislava,5600207,48.158910,17.106466,Stockholm,7400002,59.330014,18.057630
2057,5600207,7900003,Bratislava hl.st.,Ljubljana,379,4,NaN,2026-01-06,Bratislava,5600207,48.158910,17.106466,Ljubljana,7900003,46.058691,14.512937

In [28]:
df_routes_with_city_names.to_csv("Processed_Data/train_routes_scraped_processed.csv", index=False)